# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculateBuyZone.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditOpenPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditOpenPrice.setGeometry(QtCore.QRect(140, 51, 113, 31))
        self.lineEditOpenPrice.setObjectName("lineEditOpenPrice")
        self.lineEditAtr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAtr.setGeometry(QtCore.QRect(140, 101, 113, 31))
        self.lineEditAtr.setObjectName("lineEditAtr")
        self.labelLong = QtWidgets.QLabel(self.centralwidget)
        self.labelLong.setGeometry(QtCore.QRect(140, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLong.setFont(font)
        self.labelLong.setStyleSheet("color: rgb(0, 0, 255);")
        self.labelLong.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLong.setObjectName("labelLong")
        self.labelShort = QtWidgets.QLabel(self.centralwidget)
        self.labelShort.setGeometry(QtCore.QRect(140, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelShort.setFont(font)
        self.labelShort.setStyleSheet("color: rgb(255, 0, 0);")
        self.labelShort.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelShort.setObjectName("labelShort")
        self.labelOpenPrice = QtWidgets.QLabel(self.centralwidget)
        self.labelOpenPrice.setGeometry(QtCore.QRect(50, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOpenPrice.setFont(font)
        self.labelOpenPrice.setStyleSheet("color: rgb(0, 0, 0);")
        self.labelOpenPrice.setObjectName("labelOpenPrice")
        self.labelAtr = QtWidgets.QLabel(self.centralwidget)
        self.labelAtr.setGeometry(QtCore.QRect(100, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAtr.setFont(font)
        self.labelAtr.setObjectName("labelAtr")
        
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(140, 340, 141, 51))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.pushButtonCalculate.clicked.connect(self.calculateBuyZone)
        
        self.labelMaxLong = QtWidgets.QLabel(self.centralwidget)
        self.labelMaxLong.setGeometry(QtCore.QRect(140, 260, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxLong.setFont(font)
        self.labelMaxLong.setStyleSheet("color: rgb(170, 85, 255);")
        self.labelMaxLong.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMaxLong.setObjectName("labelMaxLong")
        self.labelMaxShort = QtWidgets.QLabel(self.centralwidget)
        self.labelMaxShort.setGeometry(QtCore.QRect(140, 300, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxShort.setFont(font)
        self.labelMaxShort.setStyleSheet("color: rgb(170, 85, 255);")
        self.labelMaxShort.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMaxShort.setObjectName("labelMaxShort")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 295, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buy Zone Calculator"))
        self.labelLong.setText(_translate("MainWindow", "Long Buy Zone"))
        self.labelShort.setText(_translate("MainWindow", "Short Buy Zone"))
        self.labelOpenPrice.setText(_translate("MainWindow", "Open Price"))
        self.labelAtr.setText(_translate("MainWindow", "ATR"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate!"))
        self.labelMaxLong.setText(_translate("MainWindow", "Max long price"))
        self.labelMaxShort.setText(_translate("MainWindow", "Max short price"))
    
    def calculateBuyZone(self):
        openPrice = float(self.lineEditOpenPrice.text())
        atr = float(self.lineEditAtr.text())
         # fixed 25% range of atr
        range = atr * 0.25
        incrementOpenPrice = range / 2
        long = openPrice + incrementOpenPrice
        short = openPrice - incrementOpenPrice
        maxLongPriceMovement = openPrice + atr
        maxShortPriceMovement = openPrice - atr

        self.labelLong.setText(long.__str__())
        self.labelShort.setText(short.__str__())
        self.labelMaxLong.setText(maxLongPriceMovement.__str__())
        self.labelMaxShort.setText(maxShortPriceMovement.__str__())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
